site_name: "backstage-python-app"
site_description: "Main documentation for backstage-python-app"
repo_url: https://github.com/DaniloMirandaNG/backstage-python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: "docs/index.md"
